services:
  - type: web
    name: shuttlecock-demo
    runtime: python
    plan: free
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python render_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
